In [1]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
model_name = 'sentence-transformers/bert-base-nli-mean-tokens'
model = SentenceTransformer(model_name)

In [4]:
sentences = []
dataset = pd.read_csv('..\Example_Technical_Skills.csv',skiprows=1,names=['tech_skill'],encoding='utf-8')

dataset = dataset.dropna()

for item in range(len(dataset)):
    sentences.append(dataset.tech_skill[item])

tech_skills_encode = model.encode(sentences)

In [5]:
raw_sentences = []
raw_dataset = pd.read_csv('..\Raw_Skills_Dataset.csv',skiprows=1,names=['raw_data'],encoding='utf-8')

raw_dataset = raw_dataset.dropna()

for item in range(len(raw_dataset)):
    raw_sentences.append(raw_dataset.raw_data[item])

raw_data_encode = model.encode(raw_sentences)

In [6]:
all_labels = []
ratios = []
for raw in raw_data_encode:

    ratio = np.max(cosine_similarity([raw],tech_skills_encode))
    if ratio >= 0.85:
        all_labels.append('is_tech')
        ratios.append(ratio)
        
        
    elif ratio >= 0.75 and ratio < 0.85:
        all_labels.append('is_soft')
        ratios.append(ratio)
        
        
    else:
        all_labels.append('is_raw')
        ratios.append(ratio)

In [7]:
raw_dataset["Label"] = all_labels
raw_dataset["Sim Ratio"] = ratios

raw_dataset.head(15)

                    raw_data    Label  Sim Ratio
0                   What ifs  is_soft   0.802804
1                  seniority  is_soft   0.775071
2                familiarity  is_tech   0.879318
3            functionalities  is_soft   0.804013
4                    Lambdas   is_raw   0.715957
5               Java Streams  is_tech   0.961987
6   Object Oriented analysis  is_tech   0.857175
7       Relational Databases  is_soft   0.806861
8                        SQL  is_tech   0.874838
9                        ORM  is_tech   0.897037
10                      JPA2  is_soft   0.840325
11                 Hibernate   is_raw   0.702152
12                   MyBatis  is_tech   0.874864
13                 Hibernate   is_raw   0.702152
14     code versioning tools  is_tech   0.872127